name: Notificador diario

on:
  schedule:
    - cron: '0 8 * * *'  # Todos los dias a las 08:00 UTC
  workflow_dispatch:

jobs:
  ejecutar-recordatorios:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script de recordatorio
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          URL_RECORDATORIOS: ${{ secrets.URL_RECORDATORIOS }}
        run: |
          python auto_notificador.py
